### ISSUE TITLE
To see if I can help contribute to the pointer resolvation

### ISSUE THREAD

**Issue by testforvln** [google/autocxx#1031]
Hi, I'm now trying to use autocxx to utilize some cpp library. 

When came across the object member function:
virtual int try_using_pointed_pointer(Field** pfield) = 0

I got failure in autocxx-ffi-default-gen.rs below:
#[doc = "autocxx bindings couldn't be generated: Pointer pointed to something unsupported"]
fn try_using_pointed_pointer(_uhoh: autocxx::BindingGenerationFailure) {}

I want to contribute to autocxx for the pointer resolvation like this,  but has no clue in how to implement it. Could someone give me any advice on it?

**Comment by adetaylor** [comment]
Thanks for asking!

Yes, so the very first thing is to contribute a test to `integration-tests/src/integration_test.rs`.

Initially, of course, it will fail - but you can still submit a pull request which can be merged if you mark the test as `#[ignore]`.

Once you've done that, you can run the test using
`RUST_LOG=autocxx_engine=info cargo test name-of-your-new-test -- --nocapture`

and then you can see how the API is represented by bindgen, and the various stages with which autocxx processes it.

In this particular case you'll find that we have a function `ensure_pointee_is_valid` which rejects this from a function called `convert_ptr`. You might simply be able to change `convert_ptr` to recurse if it finds a pointer-to-a-pointer instead of a pointer-to-a-path. Good luck!
