### ISSUE TITLE
autocxx_build does not support multiple include_cpp! in different files

### ISSUE THREAD

**Issue by thinkphoebe** [google/autocxx#1144]
I have multiple include_cpp! in different modules which in different .rs files, but autocxx_build::Builder::new() only supports one input .rs file.

I have tried to call autocxx_build::Builder::new() for each .rs file, but build failed with error 'Builder::init should not be called after logger initialized: SetLoggerError(())'. Every autocxx_build::Builder::new() calls env_logger::builder().init(), which should only call once. So, autocxx_build::Builder::new() can only create one instance.

- Version: 0.22.3

**Comment by adetaylor** [comment]
Thanks for the report. This is indeed a limitation of the cargo-based tooling. I'd accept pull requests to fix it, but removing that `env_logger` stuff may not be the only change required.

Because autocxx generates both Rust and C++ sides for bindings, generation of multiple sets of bindings can result in name conflicts in the symbols generated for the C++ side of the binding (violations of the one definition rule and general confusion).

That said, the command-line codegen tool, `autocxx_gen`, does allow multiple sets of input bindings - the code to handle them is [here](https://github.com/google/autocxx/blob/main/gen/cmd/src/main.rs#L262), and I think even the cargo tooling supports multiple bindings within a single .rs file, so it _may_ be relatively easy to adjust the cargo tooling to support multiple files too.
