### ISSUE TITLE
How to make the FFI public ?

### ISSUE THREAD

**Issue by astariul** [google/autocxx#1201]
## Expected Behavior

I'm trying to make the generated FFI public.

## Actual Behavior
I can't make the generated FFI public.

## Steps to Reproduce the Problem

From the simple example [demo](https://github.com/google/autocxx/tree/main/demo) :

1. Move the `include_cpp` into a `lib.rs` file.
2. In the `main.rs` file, replace it with `use autocxx_demo::ffi;`
3. Run `cargo run`
4. Get the following error : 
```
error[E0603]: module `ffi` is private
```

## Specifications

- Version: 0.23.1
- Platform: Mac

**Comment by adetaylor** [comment]
I don't know a way to do this, and I wouldn't recommend it. autocxx is intended for you to use C++ *within* your project, rather than to make an interface which you can publicly export and maintain.

If you want to use autocxx to export some APIs to other Rust crates, you should write truly Rust-idiomatic APIs to export to consumer crates, and use autocxx as an implementation detail. It's likely that future autocxx versions will make breaking changes, so it's just not a good idea to export those APIs and have anyone else rely on them.

That said, I would accept a pull request to add a [new directive for this](https://github.com/google/autocxx/blob/main/parser/src/directives.rs) which would then add `pub` to the `mod` generated [here](https://github.com/google/autocxx/blob/main/engine/src/lib.rs#L457). I'd want the directive to be accompanied by documentation stating that we don't recommend using autocxx that way.
