### ISSUE TITLE
[Question] What makes class types which have default move constructors be under a Pin?

### ISSUE THREAD

**Issue by meghprkh** [google/autocxx#1267]
## Expected Behavior

I understand that Pin prevents mem swaps for moves, since Rust assumes all objects are movable by default.

C++ has default move constructor and [`is_trivially_move_construtible`](https://en.cppreference.com/w/cpp/types/is_move_constructible) trait for such objects.

Can we use this to not wrap an object in a Pin?

## Actual Behavior

All class objects are wrapped in Pins

## Steps to Reproduce the Problem

1. Define a class in C++
1. Create binding
1. Use it using `moveit` macro

## Specifications

- Version: 0.25.0
- Platform: Linux

**Comment by adetaylor** [comment]
Yes, use `generate_pod!` instead of `generate!`. Hope that helps.

Somewhere we have an open issue to automatically detect which types are safe to be POD but I am traveling right now so I can't look it up. It's not necessarily a good idea anyway since it means small changes to C++ code could result in large required changes to the Rust code.

If you find that POD types are not behaving as you expect, feel free to open another issue.

**Comment by meghprkh** [comment]
Thanks, understood! :)
