### ISSUE TITLE
What is the purpose of RValueParamHandler?

### ISSUE THREAD

**Issue by silvanshade** [google/autocxx#1268]
I am trying to understand the design behind `RValueParamHandler`.

I see that, like `ValueParamHandler`, the `RValueParamHandler` has methods for `populate` and `get_ptr`.

But, as far as I can tell, that functionality doesn't seem to do anything particularly useful in comparison to `ValueParamHandler` since `RValueParam` only has a `get_ptr` method, whereas `ValueParam` has additionally methods for `populate_stack_space` (where copies are sometimes placed) and `do_drop`.

The reason I ask has to do with the way code is generated for binding methods that (on the Rust side) end up taking arguments as either `impl ValueParam` or `impl RValueParam`. It seems that in the latter case, unnecessary work is done in order to create a local `RValueParamHandler`, which ultimately just shuffles things around a bit until the pointer is extracted.

For a more concrete example, I was trying to implement a method that takes an array of `impl ValueParam` or `impl RValueParam`.

In the former case, I can write something like this:

```rust
unsafe fn append_vals<P, const LEN: usize>(this: Pin<&mut SmallVectorImpl<Self>>, vals: [P; LEN])
where
    P: ValueParam<Self>,
{
    let mut items: [*mut Self; LEN] = [std::ptr::null_mut(); LEN];
    let _stack: [ValueParamHandler<Self, P>; LEN] = {
        let mut stack: MaybeUninit<[ValueParamHandler<Self, P>; LEN]> = MaybeUninit::uninit();
        let arr = stack.as_mut_ptr() as *mut ValueParamHandler<Self, P>;
        for (i, val) in vals.into_iter().enumerate() {
            let ptr = arr.add(i);
            ptr.write(ValueParamHandler::default());
            let mut pin = Pin::new_unchecked(&mut *ptr);
            pin.as_mut().populate(val);
            items[i] = pin.get_ptr();
        }
        stack.assume_init()
    };
    small_vector_impl::string_ref::append_array(this, items.as_mut_ptr(), LEN);
}
```

But for `RValueParam`, it seems I can get away with a simpler version that doesn't need to create the temporary stack:

```rust
unsafe fn append_rvals<P, const LEN: usize>(this: Pin<&mut SmallVectorImpl<Self>>, vals: [P; LEN])
where
    P: RValueParam<Self>,
{
    let mut items: [*mut Self; LEN] = [std::ptr::null_mut(); LEN];
    for (i, val) in vals.into_iter().enumerate() {
        items[i] = RValueParam::get_ptr(pin!(val));
    }
    small_vector_impl::string_ref::append_array(this, items.as_mut_ptr(), LEN);
}
```

For individual arguments, creating the temporary memory doesn't seem like much of a big deal but for a case like this where there are many such arguments, it potentially becomes more noticeable.

So my question is whether there is really some rationale behind using `RValueParamHandler` or if it was more just an artifact of maintaining uniformity during code generation. Is it reasonable to ignore it for special cases like this?

**Comment by adetaylor** [comment]
Good question: I can't fully remember without poking at the code. I'm traveling for a couple of weeks so apologies if it takes a while for a proper reply.

**Comment by adetaylor** [comment]
I've spent a bit of time trying to remember the rationale here and I've been experimenting with removing `RValueParamHandler` here: https://github.com/google/autocxx/compare/remove-rvalueparamhandler

I can't quite convince myself that `RValueParamHandler` is redundant. I think it exists not just for symmetry of codegen, but also to avoid unexpected mutations of objects elsewhere in Rust-land.

When we pass an rvalue into C++ (e.g. `void function(Thingy&& thingy)`) then C++ may mutate the `thingy`. Move constructors are weird - they may mutate the original thing. For example, AIUI, the `std::string` move constructor will steal the buffer of text from the original `std::string`.

So, I think `RValueParamHandler` exists to store an extra copy of the `Thingy` that C++ can freely mutate when it eventually gets its hands on it.

It's therefore important that the `RValueParamHandler` (and its stored copy of the `Thingy`) exists for the duration of the function call into C++, and is pinned. In the case of re-entrant function calls, Rust might arbitrarily move objects. That's the reason that we store an extra copy of the `Thingy` in a way that proves it can't move.

Perhaps we're being overcautious here, because it might be OK to modify the _original_ thingy sometimes. But that probably gets hard to reason about, hence we ensure that C++ only gets its sticky mitts on an extra copy of the thingy.

It's interesting to me that you've come across a use-case to use `[R]ValueParamHandler` outside of the automatically generated bindings code. I wasn't expecting that, and I consider these types to be internal implementation details.

**Comment by silvanshade** [comment]
> It's therefore important that the `RValueParamHandler` (and its stored `Thingy`) exists for the duration of the function call into C++, and is pinned. In the case of re-entrant function calls, Rust might arbitrarily move objects. That's the reason that we store the `Thingy` in a way that proves it can't move.

Thanks for the explanation.

I think that rationale probably makes sense.

> It's interesting to me that you've come across a use-case to use `[R]ValueParamHandler` outside of the automatically generated bindings code. I wasn't expecting that, and I consider these types to be internal implementation details.

This is due to the fact that I've needed to implement several methods manually that `autocxx` was unable to generate bindings for (usually due to templates), and I've wanted to be able to support passing arguments by `impl ValueParam` or `impl RValueParam`.
