### ISSUE TITLE
Feature flag for static still contains `runtime` autocxx-bindgen/clang-sys dependencies downstream

### ISSUE THREAD

**Issue by gen-xu** [google/autocxx#1276]
## Expected Behavior

When `static` feature flag is used, the `autocxx-bindgen` should also be using static

## Actual Behavior

because `autocxx-bindgen` is added with default features that are not excluded in dependencies, while `default` of `autocxx-bindgen` contains `runtime`, adding the `static` flag unexpectedly turns on both `runtime` and `static` feature flags of `autocxx-bindgen`

## Steps to Reproduce the Problem

1. Add `autocxx` as a crate with feature flag `static` on will incur build failure

## Specifications

- Version: 0.25.0
- Platform: All

**Comment by dd-jh** [comment]
I don't think this fix was complete, because `autocxx-build` depends on `autocxx-engine` [without disabling default features](https://github.com/google/autocxx/blob/main/gen/build/Cargo.toml#L25), and the default feature set for `autocxx-engine` [includes `runtime`](https://github.com/google/autocxx/blob/main/engine/Cargo.toml#L21). So it's not possible to disable the `runtime` feature, and `clang-sys` always gets built with it enabled.

This is causing a problem with the latest version (1.8.2) of clang-sys, which [prefers to use](https://github.com/KyleMayes/clang-sys/commit/e46f0bf70a5ba9885788b0e5aa139c43bf8cebfd#diff-b063e256cdaf175454b7c43fa4321ba9ab479f0c41590773d91fb2fd23ac539bR50) its runtime-loaded `libclang` if available. That libclang doesn't work properly for me on macOS, but I can't disable it because of the above.

**Comment by jbg** [comment]
I don't think this fix was complete, because `autocxx-build` depends on `autocxx-engine` [without disabling default features](https://github.com/google/autocxx/blob/main/gen/build/Cargo.toml#L25), and the default feature set for `autocxx-engine` [includes `runtime`](https://github.com/google/autocxx/blob/main/engine/Cargo.toml#L21). So it's not possible to disable the `runtime` feature, and `clang-sys` always gets built with it enabled.

This is causing a problem with the latest version (1.8.2) of `clang-sys`, which [prefers to use](https://github.com/KyleMayes/clang-sys/commit/e46f0bf70a5ba9885788b0e5aa139c43bf8cebfd#diff-b063e256cdaf175454b7c43fa4321ba9ab479f0c41590773d91fb2fd23ac539bR50) its runtime-loaded `libclang` if available. That `libclang` doesn't work properly for me on macOS, but I can't disable it because of the above.
