### ISSUE TITLE
generator has trouble generating a vector in a vector & no conversion for Vector when passing rust vector to c++

### ISSUE THREAD

**Issue by Omicronlawful** [google/autocxx#1281]
## Expected Behavior
test should return [["Hello", World"]]
test2 should do nothing

## Actual Behavior 
`fn test (_uhoh : autocxx :: BindingGenerationFailure) { } `
test2: `impl autocxx :: ValueParam < cxx :: CxxVector < cxx :: CxxString > >)`
## Steps to Reproduce the Problem

add these functions:
```
 std::vector<std::vector<std::string>> test(){
        std::vector<std::vector<std::string>> result = {{"hello", "world"}};
        return result;
    }

    void test2(std::vector<std::string> test){
    }
```
call these functions by `test2(vec![vec!["Hello", "world", "!"]]))`and `test()`
## Specifications
these functions work:
```
std::vector<std::string> test(){
       std::vector<std::string> result = {"hello", "world"};
        return result;
    }

void test2(std::string test){
    }
```
- Version: 0.25
- Platform: Macos

**Comment by Omicronlawful** [comment]
i added the errors to the demo: https://github.com/Omicronlawful/autocxx_issue/tree/main/demo

**Comment by adetaylor** [comment]
Thanks for the report - this is expected behavior - vectors inside vectors are not supported by cxx, and the `BindingGenerationFailure` should have associated rustdoc explaining this. If it lacks rustdoc, please let me know, and I'll reopen.

Incidentally, your demo branch doesn't compile. In future it would be even better if you could raise a pull request with a minimal failing test case, per [these notes](https://google.github.io/autocxx/contributing.html#reporting-bugs)? Thanks!
