### ISSUE TITLE
'stdexcept' file not found when binding to external library

### ISSUE THREAD

**Issue by franksl** [google/autocxx#595]
Hi,
I'm tryng to generate rust bindings for the autodesk fbx c++ library.
I created a new cargo project with dependencies on autocxx.
I extracted the fbx sdk, which consists of a compiled library and a series of header files, in the /lib subdirectory.
This is my build.rs:
```
fn main() {
    // link to dynamic library
    println!("cargo:rustc-link-search=/full/path/to/lib/lib/gcc/x64/release/");
    println!("cargo:rustc-link-lib=fbxsdk");

    let path = std::path::PathBuf::from("src");
    let pathfbx = std::path::PathBuf::from("lib/include"); //this contains the header files
    let mut b = autocxx_build::build("src/main.rs", &[&path, &pathfbx], &[]).unwrap();
    b.flag_if_supported("-std=c++11")
        .compile("testautocxx");

    println!("cargo:rerun-if-changed=src/main.rs");
}
```

This is my main.rs (FbxManager is the main class of the c++ lib):
```
include_cpp! {
    #include "/full/path/to/lib/include/fbxsdk.h"
    safety!(unsafe_ffi)
    generate!("FbxManager")   
}

fn main() {
    
}
```

When trying to run "cargo build" I receive the following error:
```
--- stderr
  lib/include/fbxsdk/fbxsdk_def.h:34:10: fatal error: 'stdexcept' file not found
  lib/include/fbxsdk/fbxsdk_def.h:34:10: fatal error: 'stdexcept' file not found, err: true
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseError(AutocxxCodegenError(Bindgen(())))', build.rs:7:78
```

What am I doing wrong?
Please tell me if you need any other informations.
Thanks,
Frank

**Comment by adetaylor** [comment]
I don't exactly know, but `stdexcept` is a C++ standard header file so I'd expect it to be installed in a central location on your machine. Maybe somewhere like `/usr/include/c++/10/stdexcept`. If everything is installed correctly I'd expect bindgen to automatically find the right stuff without you needing to do anything differently in your `build.rs`.

If this is an Ubuntu-based Linux machine, maybe something like `apt-get install libstdc++-10-dev` might work? Or something along those lines?

Maybe write a test program in C++ which `#include <stdexcept>`. If you can persuade that to compile *with `clang++`* then I reckon bindgen will be able to do its job too. It's important that you use `clang++` rather than some other compiler, because bindgen is based on libclang.
