### ISSUE TITLE
How do use it on an interface with a namespace?

### ISSUE THREAD

**Issue by pkptzx** [google/autocxx#745]
eg. examples/subclass/src/messages.h -> MessageProducer  be revised as:
```c++
namespace WAHAHA
{
    namespace API
    {
        class MessageProducer
        {
        public:
            virtual std::string get_message() const = 0;
            virtual ~MessageProducer(){};
        };
    }
}
```
when I
```rust
#[is_subclass(superclass("WAHAHA::API::MessageProducer"))]
...
```
**error[E0433]: failed to resolve: use of undeclared crate or module `ffi`**

Is autocxx not support the interface for namespace?

**Comment by adetaylor** [comment]
Thanks for the report!
You may be the first person to try to use the subclass support, except for me :)

Please would you raise a pull request adding a new (failing) test case to `integration-tests/src/tests.rs`? You can run it using simply `cargo test my-new-test-name` in that directory. This will help me to diagnose and fix it quickly.

**Comment by pkptzx** [comment]
@adetaylor   Help me save the world.

**Comment by adetaylor** [comment]
OK, it looks like I already have a test for this specific case - `test_pv_subclass_namespaced_superclass` within `integration-tests/src/tests.rs`.

I suspect the problem here is that you're trying to use `is_subclass` without also having an `include_cpp!` macro. At the moment `is_subclass` is very experimental _indeed_ (even by the generally-quite-experimental standards of autocxx, represented by its 0.x version number). Please use `include_cpp! ( .. subclass! ( .. ) )` instead; maybe follow the pattern here: https://github.com/google/autocxx/blob/main/integration-tests/src/tests.rs#L7263

I _do_ expect you to find other problems with the subclass support so don't hesistate to report other issues. Thanks!
