### ISSUE TITLE
Documentation attributes for enums possibly aren't showing up

### ISSUE THREAD

**Issue by TheButlah** [google/autocxx#929]
## Expected Behavior

`cargo doc` should produce links to the enum type, along with its variants
~~The enum type should also be made `pub`~~

## Actual Behavior
![image](https://user-images.githubusercontent.com/6969415/159224136-f492604b-3bda-4d00-befa-33edb4e2029b.png)
No variants show up, and the only documentation is for the typedef

## Steps to Reproduce the Problem

1. Create a trivial enum in a C++ header
1. Set up autocxx to generate bindings for it, include the enum in a `generate!()` macro
1. `pub use ffi::MyEnum;`
1. run `cargo doc`

## Specifications

- Version: 0.17.2
- Platform: Windows 10

**Comment by TheButlah** [comment]
In fact, I think I can't even use the enum at all outside of the module file that the macro is invoked. Is it not being exported at all?

**Comment by adetaylor** [comment]
It's intended that the bindings are indeed only accessible in the immediate mod. Generally, the bindings generated by autocxx (or some equivalent tool such as bindgen) still contain some C++-specific implementation details. To expose them to other Rust code as an API, you'd probably want to wrap them in a more idiomatic Rust interface - or at least you'd want to consider doing that case-by-case. Therefore you would need to `pub use` any specific APIs which you want to export unchanged beyond your immediate module. I can't see any problems doing this - I added a test in #930 - but let me know if I'm missing something.

**Comment by kitlith** [comment]
I've been helping TheButlah a tiny bit with autocxx for their current project. Last I checked, they were either doing a `pub use ffi as <other name>` or `pub use ffi::*` so that they could use cargo doc to explore the generated bindings.

could there be something weird happening specifically with documentation of generated enums? or otherwise maybe something weird happening with the specific header being parsed?

**Comment by TheButlah** [comment]
Updated my issue to mention that I'm doing `pub use ffi::*`. I tried using *just* the enum type, and that didn't work either.
I'll go ahead and make an example repo to provide a fully reproducible example

**Comment by TheButlah** [comment]
Some further clarification on the `pub use ffi::*` - my intent is to have a `sys` crate that then gets reeported using a more idiomatic API in the actual crate.

**Comment by TheButlah** [comment]
@adetaylor I've updated the issue - I was wrong, I can in fact access the enum from third party crates. However, the part about it not being documented properly remains.

I would like `cargo doc` to document the enum along with all of its variants, when I do `pub use ffi::MyEnum`. Currently it doesn't do that.

**Comment by adetaylor** [comment]
Thanks, I'll reopen to remind myself to take a look.

**Comment by adetaylor** [comment]
Raised #951 for one issue this showed up.

**Comment by adetaylor** [comment]
Investigation results.

1. We are properly attaching documentation to the enum in our output bindgen module, and to its discriminants. (We are not subject to #951 in this case because we're passing things through unchanged from the input to the output bindgen module).
2. The output mod `use`s the type from the `cxx::bridge`. In the `cxx::bridge` we're just stating `type MyEnum = super::bindgen::root::MyEnum`.
3. We are not attaching any documentation to that `type` statement.
4. Even if we did, this gives us no opportunity to attach documentation to the enum discriminants.

Possible fixes:
1. (easy, if it works) In the output mod, `use` the bindgen mod definition not the `cxx::bridge` definition.
2. (harder) Use cxx's [extern enum support](https://cxx.rs/shared.html?highlight=enum#extern-enums)

Where we're giving a `type = XYZ` statement in the `cxx::bridge`, we need to reapply document attributes there.
